site_name: "LETO MVP"
site_url: https://leto-ai.github.io
repo_url: https://github.com/LETO-ai/leto-mvp
edit_uri: ""

remote_branch: main
remote_name: docs

theme:
  name: material
  # favicon: avatar.png
  # logo: avatar.png
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LETO-ai

copyright: "&copy; 2021 - University of Alicante & University of Havana"

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - üè† Home: index.md
  - ‚ùì Tutorial: tutorial.md
  - üìù User Guide: guide.md
  - üõ†Ô∏è Development Guide: dev.md
